### ISSUE TITLE
Traceback on load_entry_point()

### ISSUE THREAD

**Issue by mykaul** [loadtheaccumulator/glusto#39]
I did not run it for quite a while, and now something's utterly broken:
```
[root@node-0 tests]# glusto -c /root/gluster_tests_config.yml --pytest='-v -x functional/bvt/test_cvt.py  --junitxml=/tmp/cvt-junit.xml'
Traceback (most recent call last):
  File "/bin/glusto", line 11, in <module>
    load_entry_point('glusto==0.62', 'console_scripts', 'glusto')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/glusto-0.62-py2.7.egg/glusto/main.py", line 20, in <module>
    import pytest
  File "/usr/lib/python2.7/site-packages/pytest-5.1.3-py2.7.egg/pytest.py", line 6, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/usr/lib/python2.7/site-packages/pytest-5.1.3-py2.7.egg/_pytest/assertion/__init__.py", line 6, in <module>
    from _pytest.assertion import rewrite
  File "/usr/lib/python2.7/site-packages/pytest-5.1.3-py2.7.egg/_pytest/assertion/rewrite.py", line 453
    def _get_assertion_exprs(src: bytes) -> Dict[int, str]:
                                ^
SyntaxError: invalid syntax
```

Running on latest CentOS and I hope latest of everything.
I wonder if it's a Python 3 thing? While trying to upgrade pytest (via pip) I'm getting:
```
ERROR: Package 'pytest' requires a different Python: 2.7.5 not in '>=3.5'
```

**Comment by mykaul** [comment]
OK, it seems to be https://github.com/pytest-dev/pytest/issues/5519 - Pytest 5 and Python 2.x...

Which means I need to upgrade pip first so it'll install an OLDER pytest version. Duh!

**Comment by mykaul** [comment]
BTW, my pip is the latest, so I'm unsure why pytest is installed in the latest version - I need to remove it and then reinstall, then it gets installed as 4.x.

**Comment by loadtheaccumulator** [comment]
I'll check the s2i images I use to see why this hasn't come up before. I'm pretty sure RHEL 7.6 is using an old pip in that Python image. It might be that I've only been using Python3 lately. I might need to also setup some daily test runs for Fedora, CentOS, and RHEL with both Python2&3 to catch the next thing that might break through January 2020.

**Comment by mykaul** [comment]
You could try with https://github.com/mykaul/vg to get CentOS 7.x . That's where I found the issue. Regretfully, it seems to happen even when I've upgraded pip.
